import { Candidate } from '@/types';

export const mockScreeningResults: Candidate[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    matchProbability: 0.82,
    skillSimilarity: 0.78,
    fitScore: 0.85,
    yearsOfExperience: 7,
    roleRelevance: 0.9,
    skills: [
      { name: 'React', match: 0.95 },
      { name: 'TypeScript', match: 0.87 },
      { name: 'Node.js', match: 0.8 },
      { name: 'GraphQL', match: 0.75 },
      { name: 'AWS', match: 0.65 },
      { name: 'CI/CD', match: 0.7 },
    ],
    experienceSummary: 'Senior Frontend Developer with 7 years of experience building complex SPAs and leading development teams.',
    education: 'B.S. Computer Science, Stanford University',
    strengths: [
      'Strong React and TypeScript expertise',
      'Extensive experience with modern frontend architectures',
      'Proven leadership in agile development teams',
    ],
    gaps: [
      'Limited experience with backend technologies',
      'No mention of testing frameworks',
    ],
    suggestedQuestions: [
      'Can you describe a complex React component you built and how you handled state management?',
      'How do you approach TypeScript type definitions for complex data structures?',
      'Tell me about your experience with CI/CD pipelines and deployment strategies.',
    ],
  },
  {
    id: '2',
    name: 'Michael Chen',
    matchProbability: 0.68,
    skillSimilarity: 0.72,
    fitScore: 0.64,
    yearsOfExperience: 5,
    roleRelevance: 0.6,
    skills: [
      { name: 'React', match: 0.8 },
      { name: 'JavaScript', match: 0.85 },
      { name: 'CSS', match: 0.9 },
      { name: 'Redux', match: 0.75 },
      { name: 'UI/UX', match: 0.8 },
    ],
    experienceSummary: 'UI/UX Developer focused on creating responsive and accessible web applications with React.',
    education: 'M.S. Human-Computer Interaction, Carnegie Mellon University',
    strengths: [
      'Strong focus on accessibility and UI design',
      'Experience with design systems and component libraries',
      'Solid understanding of React and state management',
    ],
    gaps: [
      'Limited TypeScript experience',
      'No backend development skills mentioned',
      'No experience with GraphQL',
    ],
    suggestedQuestions: [
      'How do you ensure your React components meet accessibility standards?',
      'Describe your approach to responsive design in complex applications.',
      'What challenges have you faced implementing design systems in React?',
    ],
  },
  {
    id: '3',
    name: 'Olivia Williams',
    matchProbability: 0.92,
    skillSimilarity: 0.88,
    fitScore: 0.95,
    yearsOfExperience: 8,
    roleRelevance: 0.95,
    skills: [
      { name: 'React', match: 0.95 },
      { name: 'TypeScript', match: 0.9 },
      { name: 'Next.js', match: 0.85 },
      { name: 'GraphQL', match: 0.9 },
      { name: 'Testing', match: 0.85 },
      { name: 'Performance', match: 0.8 },
    ],
    experienceSummary: 'Full Stack Engineer specializing in React ecosystems with extensive experience in optimizing application performance.',
    education: 'B.S. Software Engineering, MIT',
    strengths: [
      'Deep expertise in React and its ecosystem',
      'Strong TypeScript and static typing skills',
      'Experience with GraphQL and API design',
      'Focus on application performance and optimization',
    ],
    gaps: [
      'Limited experience with cloud infrastructure',
    ],
    suggestedQuestions: [
      'Describe a challenging performance issue you encountered in a React application and how you solved it.',
      'How do you approach state management in large-scale React applications?',
      'What strategies do you use for testing complex React components?',
    ],
  },
  {
    id: '4',
    name: 'Jamal Adams',
    matchProbability: 0.45,
    skillSimilarity: 0.38,
    fitScore: 0.42,
    yearsOfExperience: 3,
    roleRelevance: 0.4,
    skills: [
      { name: 'React', match: 0.6 },
      { name: 'JavaScript', match: 0.65 },
      { name: 'HTML/CSS', match: 0.7 },
      { name: 'Bootstrap', match: 0.55 },
      { name: 'jQuery', match: 0.4 },
    ],
    experienceSummary: 'Frontend Developer with experience in building React applications and responsive websites.',
    education: 'B.A. Computer Science, University of Washington',
    strengths: [
      'Solid understanding of HTML, CSS, and JavaScript fundamentals',
      'Experience with React for small to medium projects',
      'Strong communication skills and team collaboration',
    ],
    gaps: [
      'Limited experience with modern React practices',
      'No TypeScript experience mentioned',
      'Lack of experience with state management beyond React\'s built-in hooks',
      'No experience with testing frameworks',
    ],
    suggestedQuestions: [
      'How do you stay updated with the latest React best practices?',
      'Describe your experience with React hooks and functional components.',
      'What approach would you take to learn TypeScript if required for this role?',
    ],
  },
  {
    id: '5',
    name: 'Emily Rodriguez',
    matchProbability: 0.76,
    skillSimilarity: 0.82,
    fitScore: 0.78,
    yearsOfExperience: 6,
    roleRelevance: 0.75,
    skills: [
      { name: 'React', match: 0.85 },
      { name: 'TypeScript', match: 0.75 },
      { name: 'Redux', match: 0.9 },
      { name: 'Jest', match: 0.8 },
      { name: 'Webpack', match: 0.7 },
      { name: 'CSS-in-JS', match: 0.85 },
    ],
    experienceSummary: 'Frontend Engineer specialized in React, Redux, and testing with extensive experience in fintech applications.',
    education: 'M.S. Computer Science, Georgia Tech',
    strengths: [
      'Strong expertise in React and Redux architecture',
      'Experience with complex state management',
      'Solid testing practices and methodology',
      'Experience in financial sector applications',
    ],
    gaps: [
      'Limited experience with GraphQL',
      'No mention of performance optimization',
    ],
    suggestedQuestions: [
      'How do you approach testing Redux state management in React applications?',
      'Describe your experience with optimizing render performance in React.',
      'What strategies do you use for managing complex form state in React?',
    ],
  },
];